### PR TITLE
Added support for ITECH6500 series PSUs

### PR DESCRIPTION
**Pull request by Duckle29**
Hi there

I'm getting ready for some automation at work using our IT6513C, and I'm already using your library with our AimTTI CPX400D PSUs :)

The addition is still untested, hence the draft PR, but once I've had a go at it with the PSU connected I'll update here.

I have yet to add the LOAD functionality and all the other advanced test features of it, but I may do so later once I need it at work. The PSU is quite fun, it can do load-dump and other automotive test profiles.

[sgoadhouse edit: removed links to attached copyrighted documents that clearly state that it is illegal to upload to electronic storage.]

### CODE REVIEW

**Comment by sgoadhouse** [comment]
Thanks for the draft PR. I took a quick look and I have no feedback. I look forward to the followup PR after testing.

**Comment by Duckle29** [comment]
Hi there.
I finally had some time to give it a test. The example code in the committed file runs as is. There were a few capitalization errors but that was about it.

I haven't checked all the added functionality, as I don't have test setups for this at work.

**Comment by Duckle29** [comment]
This does not seem to work on an RPi. Testing further

**Comment by Duckle29** [comment]
I had just forgotten to add pyserial to my requirements. oops. All good

**Comment by Duckle29** [comment]
@sgoadhouse Hi. Any more testing you want me to do on this? :)

**Comment by sgoadhouse** [comment]
Sorry, @Duckle29 , with the holidays and all, I forgot. Thanks for the poke.

**Pull request merged**
